[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "rewnozom-codemate"
version = "0.0.3"
description = "CodeMate – Din AI-drivna kodassistent"
authors = [
    {name = "Tobias Raanaes", email = "contact@rewnozom.com"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pyside6>=6.0.0",
    "anthropic>=0.3.0",
    "openai>=1.0.0",
    "python-dotenv>=0.19.0",
    "rich>=10.0.0",
    "typer>=0.4.0",
    "pyyaml>=6.0.0",
    "psutil>=5.8.0",
    "watchdog>=2.1.0",
    "transformers>=4.30.0",
    "numpy>=1.21.0",
    "pandas>=1.3.0",
    "pytest>=7.0.0",
    "black>=22.0.0",
    "flake8>=4.0.0"
]

[project.optional-dependencies]
dev = [
    "pytest-cov>=2.12.0",
    "pytest-asyncio>=0.18.0",
    "pytest-mock>=3.6.0",
    "black>=22.0.0",
    "flake8>=4.0.0",
    "mypy>=0.910",
    "isort>=5.9.0",
    "pre-commit>=2.15.0",
    "coverage>=6.2"
]

[project.scripts]
cmate = "cmate.__main__:main"

[tool.setuptools]
packages = ["cmate"]
py-modules = ["main"]

[tool.black]
line-length = 88
target-version = ["py310"]
include = '\.pyi?$'

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 88

[tool.mypy]
python_version = "3.10"
warn_return_any = true
warn_unused_configs = true
ignore_missing_imports = true

[project.urls]
"Bug Tracker" = "https://github.com/rewnozom/CodeMate/issues"