# docker-compose.dev.yml
version: '3.8'

services:
  agent:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    volumes:
      - .:/app
      - ./workspace:/app/workspace
    environment:
      - PYTHONPATH=/app
      - DEBUG=true
    ports:
      - "8000:8000"
    depends_on:
      - lm-studio
    networks:
      - agent_network

  lm-studio:
    image: lmstudio/lmstudio:latest
    ports:
      - "1234:1234"
    volumes:
      - ./models:/models
    environment:
      - MODEL_PATH=/models
    networks:
      - agent_network

networks:
  agent_network:
    driver: bridge

# docker-compose.prod.yml
version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - agent
    networks:
      - agent_network

  agent:
    build:
      context: .
      dockerfile: docker/Dockerfile.prod
    expose:
      - "8000"
    environment:
      - PYTHONPATH=/app
    volumes:
      - workspace_data:/app/workspace
    depends_on:
      - lm-studio
    networks:
      - agent_network

  lm-studio:
    image: lmstudio/lmstudio:latest
    expose:
      - "1234"
    volumes:
      - model_data:/models
    environment:
      - MODEL_PATH=/models
    networks:
      - agent_network

volumes:
  workspace_data:
  model_data:

networks:
  agent_network:
    driver: bridge