# config/development.yaml
inherit: default.yaml

general:
  debug_mode: true
  log_level: "DEBUG"

llm:
  # Optionally override non-sensitive LLM settings here
  # Note: Temperature and similar variables are loaded from .env
  prompt_optimizer:
    optimization_factor: 0.9

validation:
  strict_mode: true
  auto_fix: false
