# config/production.yaml
inherit: default.yaml

general:
  debug_mode: false
  log_level: "WARNING"

llm:
  # Temperature and similar sensitive variables remain under .env control.
  # Production-specific overrides can be added here if necessary.
  
validation:
  strict_mode: true
  auto_fix: false

storage:
  compression: true
  backup_enabled: true
  max_backups: 10

monitoring:
  metrics_interval: 30
