# config/prompts/workflow_prompts.yaml
# Advanced Workflow Management Framework - Version 3.1
# Sophisticated templates for workflow planning, execution, and validation

workflow_planning:
  content: |
    Develop comprehensive workflow strategy:

    CONTEXT:
      Task: {task}
      Environment: {context}

    Planning Framework:
    1. Workflow Architecture
       - Core Components
         * Primary objectives
         * Required resources
         * System dependencies
         * Integration points

       - Process Flow
         * Sequential steps
         * Parallel operations
         * Decision points
         * Error handlers

    2. Implementation Strategy
       - Execution Plan
         * Preparation tasks
         * Core operations
         * Validation checks
         * Cleanup activities

       - Resource Management
         * Time estimates
         * System resources
         * Dependencies
         * Constraints

    3. Risk Management
       - Risk Assessment
         * Technical risks
         * Resource risks
         * Timeline risks
         * Integration risks

       - Mitigation Strategy
         * Prevention measures
         * Recovery plans
         * Alternate paths
         * Rollback procedures

    4. Success Criteria
       - Validation Points
         * Step completion
         * Quality checks
         * Performance metrics
         * Integration tests

       - Acceptance Criteria
         * Functional requirements
         * Performance requirements
         * Quality standards
         * Documentation needs

    Provide workflow plan:
    PLAN:
      Steps: [Detailed workflow steps]
      Dependencies: [Step dependencies]
      Timeline: [Execution timeline]
      Resources: [Required resources]

    VALIDATION:
      Checkpoints: [Validation points]
      Criteria: [Success criteria]
      Metrics: [Key metrics]

    RISK:
      Analysis: [Risk assessment]
      Mitigation: [Mitigation plans]
      Recovery: [Recovery procedures]
  variables:
    - task
    - context
  description: "Enhanced workflow planning prompt with comprehensive strategy development and risk management."
  category: "workflow"
  version: "3.1"

workflow_validation:
  content: |
    Perform workflow validation analysis:

    CONTEXT:
      Workflow: {workflow}
      Results: {results}

    Validation Framework:
    1. Completion Verification
       - Step Analysis
         * Step completion status
         * Output validation
         * Error conditions
         * Performance metrics

       - Dependency Check
         * Component integration
         * Resource usage
         * System stability
         * Data consistency

    2. Quality Assessment
       - Requirements Check
         * Functional requirements
         * Performance criteria
         * Quality standards
         * Documentation status

       - Implementation Review
         * Code quality
         * Test coverage
         * Security compliance
         * Best practices

    3. Impact Analysis
       - System Effects
         * Resource utilization
         * Performance impact
         * Integration status
         * Stability assessment

       - User Impact
         * Functionality changes
         * Interface updates
         * Documentation needs
         * Training requirements

    4. Improvement Planning
       - Enhancement Areas
         * Process optimization
         * Resource efficiency
         * Error prevention
         * Documentation updates

       - Future Proofing
         * Scalability considerations
         * Maintenance needs
         * Update requirements
         * Training plans

    Provide validation report:
    VALIDATION:
      Status: [Completion status]
      Quality: [Quality assessment]
      Impact: [Impact analysis]
      Issues: [Identified issues]

    RECOMMENDATIONS:
      Improvements: [Enhancement suggestions]
      Actions: [Required actions]
      Updates: [Needed updates]
      Training: [Training needs]

    DOCUMENTATION:
      Changes: [Implementation changes]
      Lessons: [Lessons learned]
      Notes: [Important notes]
  variables:
    - workflow
    - results
  description: "Comprehensive workflow validation prompt ensuring thorough quality assessment and improvement planning."
  category: "workflow"
  version: "3.1"

workflow_monitoring:
  content: |
    Monitor workflow execution health:

    WORKFLOW:
      Status: {workflow_status}
      Metrics: {performance_metrics}
      Issues: {current_issues}

    Monitoring Framework:
    1. Performance Tracking
       - Resource usage
       - Response times
       - Error rates
       - System stability

    2. Health Assessment
       - Component status
       - Integration health
       - Data consistency
       - Service availability

    3. Issue Detection
       - Error patterns
       - Performance degradation
       - Resource constraints
       - Integration problems

    Provide monitoring report:
    STATUS:
      Health: [System health]
      Performance: [Performance status]
      Issues: [Active issues]
      Actions: [Required actions]
  variables:
    - workflow_status
    - performance_metrics
    - current_issues
  description: "New workflow monitoring prompt ensuring continuous health assessment during execution."
  category: "workflow"
  version: "3.1"